
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      # ZOO_ENABLE_AUTH: yes
      # ZOO_SERVER_USERS: admin
      # ZOO_SERVER_PASSWORDS: Dragon@12345
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-network
    healthcheck:
      # test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      zookeeper:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-network
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 9092"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka
        # condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - kafka-network 

volumes:
  kafka-manager-data:

networks:
  kafka-network: